TravelDigiatlPoint/Areas/Motorista/Controllers/MotoristaRotasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TravelDigiatlPoint.Context;
using TravelDigiatlPoint.Models;
using TravelDigiatlPoint.Repositories.Interface;
using TravelDigiatlPoint.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace TravelDigiatlPoint.Areas.Motorista.Controllers
{
    [Area("Motorista")]
    public class MotoristaRotasController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IRotasTrabalhoRepository _rotasTrabalhoRepository;

        public MotoristaRotasController(AppDbContext context, IRotasTrabalhoRepository rotasTrabalhoRepository)
        {
            _context = context;
            _rotasTrabalhoRepository = rotasTrabalhoRepository;
        }

        public IActionResult Index()
        {
            var viewModel = new FuncionarioViewModel
            {
                Funcionarios = _context.Funcionarios.Where(x => x.Cargo == Cargo.Motorista).ToList()
            };
            return View(viewModel);
        }

        public IActionResult Details(int id)
        {
            var rotas = _rotasTrabalhoRepository.Rotas
                .Where(r => r.FuncionarioId == id)
                .ToList();

            if (!rotas.Any())
            {
                return NotFound();
            }

            return View(rotas);
        }

        // GET: MotoristaRotas/StartTrip/5
        public async Task<IActionResult> StartTrip(int id)
        {
            var rota = await _context.Rotas
                .Include(r => r.Veiculo)
                .Include(r => r.Funcionario)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (rota == null)
            {
                return NotFound();
            }

            rota.DataHoraPartida = DateTime.Now;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Rotas.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return RedirectToAction("Details", new { id = rota.FuncionarioId });
        }


        // GET: MotoristaRota/EndTrip/5
        public async Task<IActionResult> EndTrip(int id)
        {
            var rota = await _context.Rotas
                .Include(r => r.Veiculo)
                .Include(r => r.Funcionario)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (rota == null)
            {
                return NotFound();
            }

            return View(rota);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EndTrip(int id, [Bind("Id,DataHoraChegada,FlDanos,ObservacaoMotorista")] Rota rotaUpdate)
        {
            var rota = await _context.Rotas
                .Include(r => r.Veiculo)
                .Include(r => r.Funcionario)
                .FirstOrDefaultAsync(r => r.Id == id);

            if (rota == null)
            {
                return NotFound();
            }

            rota.DataHoraChegada = DateTime.Now;
            rota.FlDanos = rotaUpdate.FlDanos;
            rota.ObservacaoMotorista = rotaUpdate.ObservacaoMotorista;

            //if (ModelState.IsValid)
            //{
                try
                {
                    _context.Update(rota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Rotas.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = rota.FuncionarioId });
            //}

            //return View(rota);
        }
    }
}

TravelDigiatlPoint/Areas/Motorista/Views/MotoristaRotas/Details.cshtml
@model IEnumerable<TravelDigiatlPoint.Models.Rota>

<div class="container">
    <h2>Detalhes das Viagens</h2>
    @foreach (var rota in Model)
    {
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">Viagem de @rota.Origem para @rota.Destino</h5>
                <p class="card-text"><strong>Veículo:</strong> @rota.Veiculo.CodVeiculo</p>
                <p class="card-text"><strong>Motorista:</strong> @rota.Funcionario.Nome</p>
                <p class="card-text"><strong>Data e Hora de Partida:</strong> @rota.DataHoraPartida</p>
                <p class="card-text"><strong>Data e Hora de Chegada:</strong> @rota.DataHoraChegada</p>
                <p class="card-text"><strong>Observações:</strong> @rota.ObservacaoMotorista</p>
                <a asp-controller="MotoristaRotas" asp-action="StartTrip" asp-route-id="@rota.Id"
                   class="btn btn-outline-info">Iniciar Viagem</a>
                <a asp-controller="MotoristaRotas" asp-action="EndTrip" asp-route-id="@rota.Id"
                   class="btn btn-outline-danger">Finalizar Viagem</a>
            </div>
        </div>
    }
</div>

TravelDigiatlPoint/Areas/Motorista/Views/MotoristaRotas/EndTrip.cshtml
@model TravelDigiatlPoint.Models.Rota

<div class="container">
    <h2>Finalizar Viagem</h2>
    <form asp-action="EndTrip" method="post">
        <div class="form-group">
            <label>Data e Hora de Partida:</label>
            <input type="text" class="form-control" value="@Model.DataHoraPartida" readonly />
        </div>
        <div class="form-group">
            <label>Data e Hora de Chegada:</label>
            <input type="text" class="form-control" value="@DateTime.Now" readonly />
        </div>
        <div class="form-group">
            <label>Teve algum problema com o veículo?</label>
            <input type="checkbox" class="form-control" id="flDanos" name="flDanos" />
        </div>
        <div class="form-group" id="observacaoDiv" style="display: none;">
            <label>Observação do Motorista:</label>
            <textarea class="form-control" id="observacaoMotorista" name="observacaoMotorista"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Finalizar Viagem</button>
    </form>
</div>

@section Scripts {
    <script>
        document.getElementById('flDanos').addEventListener('change', function () {
            var observacaoDiv = document.getElementById('observacaoDiv');
            if (this.checked) {
                observacaoDiv.style.display = 'block';
            } else {
                observacaoDiv.style.display = 'none';
            }
        });
    </script>
}

TravelDigiatlPoint/Areas/Motorista/Views/MotoristaRotas/Index.cshtml
@using TravelDigiatlPoint.ViewModel
@model FuncionarioViewModel

<div class="row">
    @foreach (var func in Model.Funcionarios)
    {
        <partial name="_FuncionariosResumo" for="@func" />
    }
</div>

TravelDigiatlPoint/Areas/Motorista/Views/MotoristaRotas/StartTrip.cshtml
@model TravelDigiatlPoint.Models.Rota

<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Viagem Iniciada</h2>
                <p class="card-text"><h5>Origem: @Model.Origem</h5></p>
                <p class="card-text"><h5>Destino: @Model.Destino</h5></p>
                <p class="card-text"><h6>Veículo: @Model.Veiculo.CodVeiculo</h6></p>
                <p class="card-text"><h6>Motorista: @Model.Funcionario.Nome</h6></p>
                <p class="card-text"><h6>Data e Hora de Partida: @Model.DataHoraPartida</h6></p>
                <p class="card-text"><h6>Data e Hora de Chegada: @Model.DataHoraChegada</h6></p>
                <p class="btn btn-group align-content-lg-end">
                    <a asp-controller="MotoristaRotas" asp-action="Details" asp-route-id="@Model.FuncionarioId"
                       class="btn btn-outline-info">Voltar</a>
                    <a asp-controller="MotoristaRotas" asp-action="EndTrip" asp-route-id="@Model.Id"
                       class="btn btn-outline-danger">Finalizar Viagem</a>
                </p>
            </div>
        </div>
    </div>
</div>